// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwXep9730VgSCfJPOiNbTqDCqKvT66jN0',
    appId: '1:998398348087:web:4668c486914ad431cca8b2',
    messagingSenderId: '998398348087',
    projectId: 'authfilmboxd',
    authDomain: 'authfilmboxd.firebaseapp.com',
    storageBucket: 'authfilmboxd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB69ZUdr6hW5TAQn2dgEyN_CAUEHasWe28',
    appId: '1:998398348087:android:69f6752bd67c846ecca8b2',
    messagingSenderId: '998398348087',
    projectId: 'authfilmboxd',
    storageBucket: 'authfilmboxd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPUpe3zReqDBRjOyp9DZkxirPyNFNNvUI',
    appId: '1:998398348087:ios:9ae4c60efe6aa2f9cca8b2',
    messagingSenderId: '998398348087',
    projectId: 'authfilmboxd',
    storageBucket: 'authfilmboxd.firebasestorage.app',
    iosBundleId: 'com.example.filmboxd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPUpe3zReqDBRjOyp9DZkxirPyNFNNvUI',
    appId: '1:998398348087:ios:9ae4c60efe6aa2f9cca8b2',
    messagingSenderId: '998398348087',
    projectId: 'authfilmboxd',
    storageBucket: 'authfilmboxd.firebasestorage.app',
    iosBundleId: 'com.example.filmboxd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwXep9730VgSCfJPOiNbTqDCqKvT66jN0',
    appId: '1:998398348087:web:f07fd3b6352e22e4cca8b2',
    messagingSenderId: '998398348087',
    projectId: 'authfilmboxd',
    authDomain: 'authfilmboxd.firebaseapp.com',
    storageBucket: 'authfilmboxd.firebasestorage.app',
  );
}
